# Generated by Django 3.1.6 on 2021-02-14 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Workgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_structure.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('ocupation', models.CharField(max_length=90)),
                ('experience', models.PositiveIntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vacation_days', models.PositiveIntegerField()),
                ('workgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_structure.workgroup')),
            ],
        ),
    ]
