# Generated by Django 3.1.6 on 2021-02-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_structure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='ocupation',
            new_name='occupation',
        ),
    ]
