# Generated by Django 3.1.6 on 2021-02-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_structure', '0003_auto_20210217_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='experience',
        ),
        migrations.AddField(
            model_name='employee',
            name='hired_date',
            field=models.DateField(null=True),
        ),
    ]
